In [1]:
import numpy as np 
import pandas as pd 
import statistics

In [4]:
deliveries=pd.read_csv("deliveries.csv")
deliveries.head(30)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
20,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,1,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
21,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
22,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,3,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
23,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
24,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
25,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
26,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,1,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
27,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,2,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
28,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,3,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
29,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,4,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN

# Batsman With Highest Strike Rate

In [5]:
a=deliveries.groupby('batsman')['batsman_runs'].count()

In [6]:
b=deliveries.groupby('batsman')['batsman_runs'].count()>300

In [7]:
c=a[b].index.tolist()
c

['A Mishra',
 'A Symonds',
 'AB de Villiers',
 'AC Gilchrist',
 'AD Mathews',
 'AD Russell',
 'AJ Finch',
 'AL Menaria',
 'AM Nayar',
 'AM Rahane',
 'AR Patel',
 'AT Rayudu',
 'Azhar Mahmood',
 'BB McCullum',
 'BJ Hodge',
 'CA Pujara',
 'CH Gayle',
 'CJ Anderson',
 'CL White',
 'DA Miller',
 'DA Warner',
 'DB Ravi Teja',
 'DJ Bravo',
 'DJ Hussey',
 'DPMD Jayawardene',
 'DR Smith',
 'DT Christian',
 'EJG Morgan',
 'F du Plessis',
 'G Gambhir',
 'GC Smith',
 'GH Vihari',
 'GJ Bailey',
 'GJ Maxwell',
 'HH Gibbs',
 'HH Pandya',
 'HM Amla',
 'Harbhajan Singh',
 'IK Pathan',
 'J Botha',
 'JA Morkel',
 'JC Buttler',
 'JD Ryder',
 'JEC Franklin',
 'JH Kallis',
 'JP Duminy',
 'JP Faulkner',
 'JR Hopes',
 'KA Pollard',
 'KC Sangakkara',
 'KD Karthik',
 'KH Pandya',
 'KK Nair',
 'KL Rahul',
 'KM Jadhav',
 'KP Pietersen',
 'KS Williamson',
 'LMP Simmons',
 'LR Shukla',
 'LRPL Taylor',
 'M Manhas',
 'M Vijay',
 'M Vohra',
 'MA Agarwal',
 'MC Henriques',
 'MEK Hussey',
 'MK Pandey',
 'MK Tiwary',
 'ML Hayden',
 'MS Bisla',
 'MS Dhoni',
 'MV Boucher',
 'Mandeep Singh',
 'N Rana',
 'NLTC Perera',
 'NV Ojha',
 'OA Shah',
 'P Kumar',
 'PA Patel',
 'PC Valthaty',
 'PP Chawla',
 'Q de Kock',
 'R Dravid',
 'RA Jadeja',
 'RG Sharma',
 'RR Pant',
 'RS Bopara',
 'RV Uthappa',
 'S Badrinath',
 'S Dhawan',
 'S Sohal',
 'SA Asnodkar',
 'SA Yadav',
 'SC Ganguly',
 'SE Marsh',
 'SK Raina',
 'SPD Smith',
 'SR Tendulkar',
 'SR Watson',
 'SS Iyer',
 'SS Tiwary',
 'ST Jayasuriya',
 'STR Binny',
 'SV Samson',
 'Shakib Al Hasan',
 'TL Suman',
 'TM Dilshan',
 'UBT Chand',
 'V Kohli',
 'V Sehwag',
 'WP Saha',
 'Y Venugopal Rao',
 'YK Pathan',
 'Yuvraj Singh']

# Finding Mean and Standarad Deviation

In [8]:
new_batsman=deliveries[deliveries['batsman'].isin(c)]

In [9]:
new_batsman_runs=new_batsman.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False)
new_batsman_runs.head()

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

In [10]:
new_batsman_balls=new_batsman.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False)
new_batsman_balls.head()

batsman
V Kohli      3494
G Gambhir    3433
SK Raina     3369
RG Sharma    3274
S Dhawan     3005
Name: batsman_runs, dtype: int64

In [11]:
strike_rate=[]
strike_rate=(((new_batsman_runs/new_batsman_balls)*100).sort_values(ascending=False))
strike_rate.head()

batsman
AD Russell    164.000000
GJ Maxwell    157.564103
KH Pandya     153.354633
V Sehwag      148.827059
RR Pant       148.031496
Name: batsman_runs, dtype: float64

In [12]:
mean_batsman=statistics.mean(((new_batsman_runs/new_batsman_balls)*100).sort_values(ascending=False))
mean_batsman

123.12569532943265

In [13]:
sd_batsman=statistics.stdev(((new_batsman_runs/new_batsman_balls)*100).sort_values(ascending=False))
sd_batsman

12.593434238460521

# Bowlers Economy Rate

In [14]:
deliveries['dismissal_kind'].value_counts()

caught                   4373
bowled                   1382
run out                   755
lbw                       455
stumped                   243
caught and bowled         211
hit wicket                  9
retired hurt                9
obstructing the field       1
Name: dismissal_kind, dtype: int64

In [15]:
dismissal=['caught','bowled','lbw','stumped','caught and bowled','hit wicket']
out=deliveries[deliveries['dismissal_kind'].isin(dismissal)]
bowler=out.groupby('bowler')['dismissal_kind'].count().sort_values(ascending=False)

In [16]:
x=deliveries.groupby('bowler')['total_runs'].count()
y=deliveries.groupby('bowler')['total_runs'].count()>100
d=x[y].index.tolist()
d

['A Ashish Reddy',
 'A Chandila',
 'A Choudhary',
 'A Kumble',
 'A Mishra',
 'A Mithun',
 'A Nehra',
 'A Singh',
 'A Symonds',
 'A Zampa',
 'AA Chavan',
 'AB Agarkar',
 'AB Dinda',
 'AB McDonald',
 'AC Thomas',
 'AD Mascarenhas',
 'AD Mathews',
 'AD Russell',
 'AF Milne',
 'AG Murtaza',
 'AJ Tye',
 'AL Menaria',
 'AM Nayar',
 'AM Salvi',
 'AN Ahmed',
 'AR Patel',
 'AS Rajpoot',
 'Anand Rajan',
 'Ankit Sharma',
 'Ankit Soni',
 'Anureet Singh',
 'Azhar Mahmood',
 'B Akhil',
 'B Kumar',
 'B Lee',
 'BA Bhatt',
 'BA Stokes',
 'BAW Mendis',
 'BB Sran',
 'BCJ Cutting',
 'BE Hendricks',
 'BJ Hodge',
 'BW Hilfenhaus',
 'Basil Thampi',
 'Bipul Sharma',
 'C de Grandhomme',
 'CH Gayle',
 'CH Morris',
 'CJ Anderson',
 'CJ Jordan',
 'CK Langeveldt',
 'CR Brathwaite',
 'CR Woakes',
 'CRD Fernando',
 'D Wiese',
 'DE Bollinger',
 'DJ Bravo',
 'DJ Hooda',
 'DJ Hussey',
 'DJG Sammy',
 'DL Vettori',
 'DP Nannes',
 'DP Vijaykumar',
 'DR Smith',
 'DS Kulkarni',
 'DT Christian',
 'DW Steyn',
 'FH Edwards',
 'GB Hogg',
 'GD McGrath',
 'GJ Maxwell',
 'HH Pandya',
 'HV Patel',
 'Harbhajan Singh',
 'Harmeet Singh',
 'I Sharma',
 'IC Pandey',
 'IK Pathan',
 'Imran Tahir',
 'Iqbal Abdulla',
 'J Botha',
 'J Suchith',
 'J Syed Mohammad',
 'J Theron',
 'J Yadav',
 'JA Morkel',
 'JD Ryder',
 'JD Unadkat',
 'JDP Oram',
 'JE Taylor',
 'JEC Franklin',
 'JH Kallis',
 'JJ Bumrah',
 'JO Holder',
 'JP Duminy',
 'JP Faulkner',
 'JR Hopes',
 'Jaskaran Singh',
 'Joginder Sharma',
 'K Rabada',
 'KA Pollard',
 'KC Cariappa',
 'KH Pandya',
 'KJ Abbott',
 'KK Cooper',
 'KMDN Kulasekara',
 'KP Appanna',
 'KP Pietersen',
 'KV Sharma',
 'KW Richardson',
 'Kamran Khan',
 'Karanveer Singh',
 'Kuldeep Yadav',
 'L Balaji',
 'LR Shukla',
 'M Ashwin',
 'M Kartik',
 'M Morkel',
 'M Muralitharan',
 'M Ntini',
 'M de Lange',
 'MA Starc',
 'MC Henriques',
 'MF Maharoof',
 'MG Johnson',
 'MJ McClenaghan',
 'MM Patel',
 'MM Sharma',
 'MN Samuels',
 'MP Stoinis',
 'MR Marsh',
 'MS Gony',
 'Mohammad Asif',
 'Mohammed Shami',
 'Mohammed Siraj',
 'Mustafizur Rahman',
 'NLTC Perera',
 'NM Coulter-Nile',
 'P Amarnath',
 'P Awana',
 'P Kumar',
 'P Negi',
 'P Parameswaran',
 'P Sahu',
 'P Suyal',
 'PC Valthaty',
 'PJ Cummins',
 'PJ Sangwan',
 'PP Chawla',
 'PP Ojha',
 'PV Tambe',
 'Pankaj Singh',
 'Parvez Rasool',
 'R Ashwin',
 'R Bhatia',
 'R Dhawan',
 'R McLaren',
 'R Rampaul',
 'R Sathish',
 'R Sharma',
 'R Shukla',
 'R Tewatia',
 'R Vinay Kumar',
 'RA Jadeja',
 'RE van der Merwe',
 'RG Sharma',
 'RJ Harris',
 'RP Singh',
 'RR Powar',
 'RR Raje',
 'RS Bopara',
 'Rashid Khan',
 'S Aravind',
 'S Badree',
 'S Gopal',
 'S Kaul',
 'S Kaushik',
 'S Ladda',
 'S Nadeem',
 'S Narwal',
 'S Randiv',
 'S Sreesanth',
 'S Tyagi',
 'SB Bangar',
 'SB Jakati',
 'SB Styris',
 'SB Wagh',
 'SC Ganguly',
 'SE Bond',
 'SJ Srivastava',
 'SK Raina',
 'SK Trivedi',
 'SK Warne',
 'SL Malinga',
 'SM Pollock',
 'SMSM Senanayake',
 'SN Thakur',
 'SP Narine',
 'SR Watson',
 'ST Jayasuriya',
 'STR Binny',
 'SW Tait',
 'Sandeep Sharma',
 'Shahid Afridi',
 'Shakib Al Hasan',
 'Shivam Sharma',
 'Shoaib Ahmed',
 'Sohail Tanvir',
 'T Thushara',
 'TA Boult',
 'TG Southee',
 'TL Suman',
 'TM Dilshan',
 'TS Mills',
 'UT Yadav',
 'Umar Gul',
 'V Kohli',
 'V Pratap Singh',
 'V Sehwag',
 'VR Aaron',
 'VRV Singh',
 'VS Malik',
 'VY Mahesh',
 'WD Parnell',
 'WPUJC Vaas',
 'Washington Sundar',
 'Y Venugopal Rao',
 'YA Abdulla',
 'YK Pathan',
 'YS Chahal',
 'Yuvraj Singh',
 'Z Khan']

#  Finding Mean And Standard Deviation

In [17]:
new_bowler=deliveries[deliveries['bowler'].isin(d)]
new_bowler_runs=new_bowler.groupby('bowler')['total_runs'].sum().sort_values(ascending=False)
new_bowler_runs

bowler
Harbhajan Singh      3453
P Kumar              3342
PP Chawla            3315
A Mishra             3305
SL Malinga           3034
R Vinay Kumar        2976
Z Khan               2860
DJ Bravo             2815
UT Yadav             2802
IK Pathan            2711
R Ashwin             2552
RA Jadeja            2540
A Nehra              2537
SR Watson            2490
RP Singh             2417
B Kumar              2410
JA Morkel            2409
PP Ojha              2399
DW Steyn             2375
JH Kallis            2348
I Sharma             2291
M Morkel             2136
AB Dinda             2103
MM Sharma            2088
SP Narine            2085
L Balaji             2083
R Bhatia             2059
SK Trivedi           1944
DS Kulkarni          1918
JP Faulkner          1849
                     ...
DP Vijaykumar         205
AM Salvi              205
S Narwal              203
CK Langeveldt         199
Umar Gul              198
K Rabada              198
TL Suman              198
J Yadav               197
Washington Sundar     189
AF Milne              185
KJ Abbott             182
Jaskaran Singh        174
M de Lange            171
JE Taylor             167
Shivam Sharma         165
T Thushara            164
FH Edwards            160
TS Mills              157
S Gopal               155
Shoaib Ahmed          154
P Suyal               154
P Sahu                152
SB Wagh               147
AJ Tye                146
Ankit Soni            145
AL Menaria            144
A Choudhary           144
R Tewatia             141
C de Grandhomme       136
KMDN Kulasekara       122
Name: total_runs, Length: 232, dtype: int64

In [18]:
new_bowler_balls=new_bowler.groupby('bowler')['total_runs'].count().sort_values(ascending=False)
new_bowler_balls

bowler
Harbhajan Singh    2989
A Mishra           2703
SL Malinga         2694
P Kumar            2637
PP Chawla          2594
R Ashwin           2359
Z Khan             2276
R Vinay Kumar      2161
DW Steyn           2159
IK Pathan          2113
DJ Bravo           2110
B Kumar            2054
UT Yadav           2033
A Nehra            1974
RA Jadeja          1962
SR Watson          1961
SP Narine          1956
PP Ojha            1945
RP Singh           1874
JA Morkel          1807
JH Kallis          1799
I Sharma           1713
M Morkel           1699
R Bhatia           1661
AB Dinda           1589
M Muralitharan     1581
L Balaji           1574
MM Sharma          1566
SK Trivedi         1557
DS Kulkarni        1485
                   ...
FH Edwards          150
RR Raje             144
T Thushara          144
R Sathish           144
S Ladda             141
Mohammed Siraj      141
V Sehwag            138
K Rabada            137
P Amarnath          132
R Shukla            130
AJ Tye              128
R Tewatia           128
JE Taylor           122
S Gopal             116
M de Lange          116
AF Milne            115
Shivam Sharma       114
AL Menaria          113
S Narwal            113
Ankit Soni          112
TS Mills            111
Jaskaran Singh      111
SB Wagh             108
A Choudhary         108
KMDN Kulasekara     107
P Suyal             107
P Sahu              107
Shoaib Ahmed        103
KJ Abbott           102
C de Grandhomme     102
Name: total_runs, Length: 232, dtype: int64

In [19]:
bowler_overs=(new_bowler_balls/6)

In [20]:
economy_rate=[]
economy_rate=(new_bowler_runs/bowler_overs).sort_values(ascending=True)
economy_rate.head()

bowler
Sohail Tanvir        6.226415
Washington Sundar    6.230769
A Chandila           6.282051
SP Narine            6.395706
FH Edwards           6.400000
Name: total_runs, dtype: float64

In [21]:
mean_bowler=statistics.mean((new_bowler_runs/bowler_overs).sort_values(ascending=False))
mean_bowler

7.969271274565699

In [22]:
sd_bowler=statistics.stdev((new_bowler_runs/bowler_overs).sort_values(ascending=False))
sd_bowler

0.8270323641957655

# Function Comparing Batsmans Vs Bowlers

In [23]:
def batsman_vs_bowler():
    print("Enter Batsman name")
    batsman_name=input()
    score=strike_rate[batsman_name]
    z_batsman=(score-mean_batsman)/sd_batsman

    print("Enter Bowler name")
    bowler_name=input()
    score1=economy_rate[bowler_name]
    z_bowler=(mean_bowler-score1)/sd_bowler
    
    if(z_batsman>z_bowler):
        print("The player better among them is:"+batsman_name)
    else:
        print("The player better among them is:"+bowler_name)

In [24]:
batsman_vs_bowler()

Enter Batsman name
V Kohli
Enter Bowler name
B Kumar
The player better among them is:B Kumar

In [28]:
batsman_vs_bowler()

Enter Batsman name
S Dhawan
Enter Bowler name
Harbhajan Singh
The player better among them is:Harbhajan Singh